# A docker image from Docker Hub to use as the build environment
image: maven:3.5.0-jdk-9-slim

clone:           # the 'clone' section 
  depth: 5       # the depth, in this case the clone will contain last five commits

pipelines:
  default:
    - step:
        script: # Runs OPSIN's tests and assembly a fat jar containing all modules
          - mvn clean test package assembly:assembly
